### PR TITLE
Update social share images

### LINKED ISSUE #15: Update Social Share Images
Simply remove 2016, center "OpenStreetStreetMap Funding Drive", generate all needed formats, and make a PR updating the images in this repo.

### PR DESCRIPTION
**Pull request by engelsjk**
This pull request updates the social share images osm_banner, osm_slide and twitter-card. The text '2016' has been removed from all images, font styles have been matched as close as possible and png/jpg file formats have been generated.

Fixes #15

### CODE REVIEW

**Comment by Firefishy** [comment]
@mikelmaron If you could sign this off...

**Comment by mikelmaron** [comment]
@engelsjk thank you! one request -- the dimensions of `osm_slide.jpg` have changed. can you fix that so the dimensions are the same.

**Comment by engelsjk** [comment]
Ah sorry about that! Should be fixed now.

**Comment by mikelmaron** [comment]
@Firefishy went ahead and merged :)

**Pull request merged**
