### PR TITLE
[WIP] Monthly payments

### PR DESCRIPTION
**Pull request by Zverik**
This is an untested implementation for monthly donations via our donations form.

What's missing: recurring donations will not show up in the donor list, except for the first one.

Looks like this:

### CODE REVIEW

**Comment by grischard** [comment]
Hello from the Treasurer. I'm confused by this PR, because I'm seeing recurring donations coming in!

**Comment by Firefishy** [comment]
The recurring payments are from the Wiki, there is a monthly donation link there.

**Comment by grischard** [comment]
Ahhh!

Before anyone works on this too much, I'd like to eventually move this to CiviCRM to centralise our accounting.

**Comment by Firefishy** [comment]
@Zverik Still WIP?

**Comment by Zverik** [comment]
Well I don't work on this. I believe nothing in the API has been changed in the past two years, so this should work. But I'd very much like for somebody to test this. Both the subscription and the donor list issue.

**Comment by Firefishy** [comment]
I am going to close this, donations have moved to https://supporting.openstreetmap.org/ which uses CiviCRM.

**Comment by Firefishy** [comment]
PS: Thank you!

**Pull request closed without merging**
